// PRODUCTS

export const GET_PRODUCT_LIST_REQUEST = 'GET_PRODUCT_LIST_REQUEST'
export const GET_PRODUCT_LIST_SUCCESSS = 'GET_PRODUCT_LIST_SUCCESSS'
export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST'
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'

// Auth
// export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
// export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'
export const SHOW_MESSAGE_SUCCESS = 'SHOW_MESSAGE_SUCCESS'
export const SIGNIN_USER = 'SIGNIN_USER'
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const STATUS_CLEAN = 'STATUS_CLEAN'
export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'

// MODAL
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const OPEN_MODAL = 'OPEN_MODAL'

// LOADER
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER'
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER'
